# syntax=docker/dockerfile:1
# this container brings together several geospatial python libriarys
# and tools for working with grib data it is build on top of the microsoft
# devcontainer ubuntu-22.04 base image 
ARG BASE_REGISTRY=mcr.microsoft.com \
    BASE_IMAGE=vscode/devcontainers/base \
    BASE_TAG=ubuntu-22.04
    
FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG} as base

WORKDIR /
#
RUN apt-get update -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --fix-missing --no-install-recommends \
        # proj
        # libproj-dev=8.2.1-1 \
        # # geos
        # libgeos-dev=3.10.2-1 \
        # # gdal
        # libgdal-dev=3.4.1+dfsg-1build4 \
        # python
        python3-pip 
        # tensorflow
        # nvidia-driver-510 \
        # nvidia-dkms-510 \
    # && rm -rf /var/lib/apt/lists/*
    
RUN python3 -m pip install tensorflow

RUN apt-get update -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        software-properties-common \
    # python repository
    && add-apt-repository -y \
        ppa:deadsnakes/ppa \
    # gpu repository
    && add-apt-repository -y \
        ppa:graphics-drivers/ppa \
    # update the new repos
    && apt-get update -y  \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        nvidia-cuda-toolkit \
        libcudart11.0
#         nvidia-driver-510 \
#         nvidia-dkms-510 \
#         # 2022-07-28 13:53:18.965185: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
        
RUN python3 -c "import tensorflow as tf; print(tf.test.gpu_device_name())"
# docker build -t leaver/gpu -f Dockerfile.test . && docker run --runtime=nvidia -it --rm  leaver2000/gpu