
# docker build -t leaver/dev:1.0.0 -f dockerfile.dev . && docker run --gpus all --rm -it --shm-size=1g --ulimit memlock=-1 -p 8888:8888 -p 8787:8787 -p 8786:8786 leaver/dev:1.0.0
# docker run --gpus all --rm -it --shm-size=1g --ulimit memlock=-1 -p 8888:8888 -p 8787:8787 -p 8786:8786 leaver/rapidsai-runtime:1.0.0




# ######################### NVIDIA #########################
# NVIDIA-SMI 515.57       Driver Version: 516.59       CUDA Version: 11.7     


FROM ubuntu:20.04 as base
USER root
ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash","-c"]
# extending the nvidia/cuda base image
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
    wget git zsh \
    && rm -rf /var/lib/apt/lists/*
# install zsh & Uses "robbyrussell" theme (original Oh My Zsh theme), with no plugins
WORKDIR /tmp/zsh
COPY bin/zsh-in-docker.sh .
RUN ./zsh-in-docker.sh -t robbyrussell && rm -rf /tmp/zsh
# install miniconda
WORKDIR /tmp
ARG CONDA_PREFIX=/opt/miniconda
ENV PATH=${CONDA_PREFIX}/bin:$PATH
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && /bin/bash Miniconda3-latest-Linux-x86_64.sh -b -p $CONDA_PREFIX \
    && rm -f Miniconda3-latest-Linux-x86_64.sh \
    && conda update conda \
    && conda init bash zsh

FROM base as rapids
RUN conda create -n rapids -c rapidsai-nightly -c nvidia -c conda-forge  \
    python=3.9 \
    cudf=22.08 cudatoolkit=11.5 \
    jupyterlab 


FROM base as tensorflow
SHELL ["/bin/bash","-c"]
RUN conda create -n tensorflow -c conda-forge  \
    python=3.9 pip
SHELL ["conda", "run", "-n", "tensorflow", "/bin/bash", "-c"]

RUN python -m pip install --upgrade pip \
    && pip install tensorflow-gpu


FROM base as final
COPY --from=tensorflow /opt/miniconda/envs/tensorflow /opt/miniconda/envs/tensorflow
COPY --from=rapids /opt/miniconda/envs/rapids /opt/miniconda/envs/rapids
RUN echo source activate tensorflow >> ~/.zshrc
# RUN /bin/zsh -c "source activate tensorflow"
ENTRYPOINT [ "/bin/zsh" ]
# ENTRYPOINT [ "/bin/zsh" ]
# CMD [ "python", "test.py" ]
# \
# tensorflow=2.8.1=cuda112py39h01bd6f0_0 \
# tensorflow-base=2.8.1=cuda112py39he716a45_0 \
# tensorflow-estimator=2.8.1=cuda112py39hd320b7a_0
# RUN python -c "import tensorflow as tf;print(tf.config.list_physical_devices('GPU'))"
# RUN python -c "import tensorflow as tf;print([tf.config.experimental.get_device_details(gpu) for gpu in tf.config.list_physical_devices('GPU')])"
# RUN python -c "import cartopy.crs as ccrs"
# RUN conda install -y -n venv -c conda-forge tensorflow-gpu

# RUN python -c tf.config.list_physical_devices('GPU')

# RUN conda install --name venv -c rapidsai \

#     cudf=22.06.01

# RUN conda install --name venv -c conda-forge  \
#     tensorflow-base=2.8.1

# RUN conda create --name venv -c conda-forge -c rapidsai \
#     abseil-cpp=20210324.2 \
#     arrow-cpp=7.0.0 \
#     grpc-cpp=1.45.2 \
#     libgoogle-cloud=1.40.2 \
#     orc=1.7.3-h6c59b99_1 \
#     pyarrow=7.0.0 \
#     protobuf=3.20.1

ENV TF_CPP_MIN_LOG_LEVEL="1"
# RUN conda install -n venv -c conda-forge tensorflow-gpu

# tensorflow-gpu
# SHELL ["/bin/bash","-c"]
# RUN python3.10 -m venv /opt/venv
# ENV PATH="/opt/venv/bin:$PATH"
# RUN pip install --upgrade --no-cache-dir pip \
#     && pip install --no-cache-dir tensorflow-gpu==2.9.1
# ARG USERNAME=vscode
# ARG USER_UID=1000
# ARG USER_GID=$USER_UID

# SHELL ["/bin/bash", "-o", "pipefail", "-c"]
# # create a new user
# # CREDIT: https://github.com/deluan/zsh-in-docker/blob/master/Dockerfile
# RUN groupadd --gid $USER_GID $USERNAME \
#     && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
#     && apt-get update \
#     && apt-get install -y sudo wget \
#     && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
#     && chmod 0440 /etc/sudoers.d/$USERNAME \
#     # clean up
#     && apt-get autoremove -y \
#     && apt-get clean -y \
#     && rm -rf /var/lib/apt/lists/*


# USER $USERNAME



## Package Plan ##

#   environment location: /opt/miniconda/envs/venv

#   added / updated specs:
#     - tensorflow-gpu


# The following packages will be downloaded:

#     package                    |            build
#     ---------------------------|-----------------
#     abseil-cpp-20210324.2      |       h9c3ff4c_0        1010 KB  conda-forge
#     absl-py-1.2.0              |     pyhd8ed1ab_0          94 KB  conda-forge
#     aiohttp-3.8.1              |   py39hb9d737c_1         565 KB  conda-forge
#     aiosignal-1.2.0            |     pyhd8ed1ab_0          12 KB  conda-forge
#     arrow-cpp-7.0.0            |py39he577829_7_cuda        24.3 MB  conda-forge
#     astunparse-1.6.3           |     pyhd8ed1ab_0          15 KB  conda-forge
#     async-timeout-4.0.2        |     pyhd8ed1ab_0           9 KB  conda-forge
#     attrs-22.1.0               |     pyh71513ae_1          48 KB  conda-forge
#     blinker-1.4                |             py_1          13 KB  conda-forge
#     brotlipy-0.7.0             |py39hb9d737c_1004         342 KB  conda-forge
#     cached-property-1.5.2      |       hd8ed1ab_1           4 KB  conda-forge
#     cached_property-1.5.2      |     pyha770c72_1          11 KB  conda-forge
#     certifi-2022.6.15          |   py39hf3d152e_0         155 KB  conda-forge
#     cffi-1.15.1                |   py39he91dace_0         229 KB  conda-forge
#     charset-normalizer-2.1.0   |     pyhd8ed1ab_0          35 KB  conda-forge
#     click-8.1.3                |   py39hf3d152e_0         146 KB  conda-forge
#     cryptography-37.0.4        |   py39hd97740a_0         1.5 MB  conda-forge
#     cudnn-8.4.1.50             |       hed8a83a_0       618.4 MB  conda-forge
#     frozenlist-1.3.1           |   py39hb9d737c_0          44 KB  conda-forge
#     gast-0.5.3                 |     pyhd8ed1ab_0          20 KB  conda-forge
#     giflib-5.2.1               |       h36c2ea0_2          77 KB  conda-forge
#     google-auth-2.10.0         |     pyh6c4a22f_0          90 KB  conda-forge
#     google-auth-oauthlib-0.4.6 |     pyhd8ed1ab_0          19 KB  conda-forge
#     google-pasta-0.2.0         |     pyh8c360ce_0          42 KB  conda-forge
#     grpc-cpp-1.45.2            |       hd8f4eba_3         4.7 MB  conda-forge
#     grpcio-1.45.0              |   py39h0f497a6_0         2.5 MB  conda-forge
#     h5py-3.7.0                 |nompi_py39h63b1161_100         1.3 MB  conda-forge
#     hdf5-1.12.1                |nompi_h2386368_104         3.5 MB  conda-forge
#     icu-70.1                   |       h27087fc_0        13.5 MB  conda-forge
#     idna-3.3                   |     pyhd8ed1ab_0          55 KB  conda-forge
#     importlib-metadata-4.11.4  |   py39hf3d152e_0          33 KB  conda-forge
#     jpeg-9e                    |       h166bdaf_2         269 KB  conda-forge
#     keras-2.8.0                |     pyhd8ed1ab_0         879 KB  conda-forge
#     keras-preprocessing-1.1.2  |     pyhd8ed1ab_0          34 KB  conda-forge
#     libgoogle-cloud-1.40.2     |       habd0e3a_0         9.2 MB  conda-forge
#     libpng-1.6.37              |       h753d276_3         331 KB  conda-forge
#     markdown-3.4.1             |     pyhd8ed1ab_0          65 KB  conda-forge
#     markupsafe-2.1.1           |   py39hb9d737c_1          22 KB  conda-forge
#     multidict-6.0.2            |   py39hb9d737c_1          51 KB  conda-forge
#     nccl-2.13.4.1              |       h0800d71_0       133.8 MB  conda-forge
#     oauthlib-3.2.0             |     pyhd8ed1ab_0          90 KB  conda-forge
#     opt_einsum-3.3.0           |     pyhd8ed1ab_1          53 KB  conda-forge
#     orc-1.7.3                  |       h6c59b99_1         1.1 MB  conda-forge
#     pyarrow-7.0.0              |py39h1ed2e5d_7_cuda         3.0 MB  conda-forge
#     pyasn1-0.4.8               |             py_0          53 KB  conda-forge
#     pyasn1-modules-0.2.7       |             py_0          60 KB  conda-forge
#     pycparser-2.21             |     pyhd8ed1ab_0         100 KB  conda-forge
#     pyjwt-2.4.0                |     pyhd8ed1ab_0          19 KB  conda-forge
#     pyopenssl-22.0.0           |     pyhd8ed1ab_0          49 KB  conda-forge
#     pysocks-1.7.1              |   py39hf3d152e_5          28 KB  conda-forge
#     python-flatbuffers-2.0     |     pyhd8ed1ab_0          28 KB  conda-forge
#     pyu2f-0.1.5                |     pyhd8ed1ab_0          31 KB  conda-forge
#     requests-2.28.1            |     pyhd8ed1ab_0          53 KB  conda-forge
#     requests-oauthlib-1.3.1    |     pyhd8ed1ab_0          22 KB  conda-forge
#     rsa-4.9                    |     pyhd8ed1ab_0          29 KB  conda-forge
#     scipy-1.9.0                |   py39h8ba3f38_0        26.2 MB  conda-forge
#     tensorboard-2.8.0          |     pyhd8ed1ab_1         5.2 MB  conda-forge
#     tensorboard-data-server-0.6.0|   py39hd97740a_2         3.1 MB  conda-forge
#     tensorboard-plugin-wit-1.8.1|     pyhd8ed1ab_0         668 KB  conda-forge
#     tensorflow-2.8.1           |cuda112py39h01bd6f0_0          26 KB  conda-forge
#     tensorflow-base-2.8.1      |cuda112py39he716a45_0       396.2 MB  conda-forge
#     tensorflow-estimator-2.8.1 |cuda112py39hd320b7a_0         653 KB  conda-forge
#     tensorflow-gpu-2.8.1       |cuda112py39h0bbbad9_0          26 KB  conda-forge
#     termcolor-1.1.0            |     pyhd8ed1ab_3           8 KB  conda-forge
#     typing-extensions-4.3.0    |       hd8ed1ab_0           8 KB  conda-forge
#     urllib3-1.26.11            |     pyhd8ed1ab_0         102 KB  conda-forge
#     werkzeug-2.2.1             |     pyhd8ed1ab_0         238 KB  conda-forge
#     wrapt-1.14.1               |   py39hb9d737c_0          50 KB  conda-forge
#     yarl-1.7.2                 |   py39hb9d737c_2         132 KB  conda-forge
#     zipp-3.8.1                 |     pyhd8ed1ab_0          13 KB  conda-forge
#     ------------------------------------------------------------
#                                            Total:        1.23 GB

# The following NEW packages will be INSTALLED:

#   absl-py            conda-forge/noarch::absl-py-1.2.0-pyhd8ed1ab_0
#   aiohttp            conda-forge/linux-64::aiohttp-3.8.1-py39hb9d737c_1
#   aiosignal          conda-forge/noarch::aiosignal-1.2.0-pyhd8ed1ab_0
#   astunparse         conda-forge/noarch::astunparse-1.6.3-pyhd8ed1ab_0
#   async-timeout      conda-forge/noarch::async-timeout-4.0.2-pyhd8ed1ab_0
#   attrs              conda-forge/noarch::attrs-22.1.0-pyh71513ae_1
#   blinker            conda-forge/noarch::blinker-1.4-py_1
#   brotlipy           conda-forge/linux-64::brotlipy-0.7.0-py39hb9d737c_1004
#   cached-property    conda-forge/noarch::cached-property-1.5.2-hd8ed1ab_1
#   cached_property    conda-forge/noarch::cached_property-1.5.2-pyha770c72_1
#   certifi            conda-forge/linux-64::certifi-2022.6.15-py39hf3d152e_0
#   cffi               conda-forge/linux-64::cffi-1.15.1-py39he91dace_0
#   charset-normalizer conda-forge/noarch::charset-normalizer-2.1.0-pyhd8ed1ab_0
#   click              conda-forge/linux-64::click-8.1.3-py39hf3d152e_0
#   cryptography       conda-forge/linux-64::cryptography-37.0.4-py39hd97740a_0
#   cudnn              conda-forge/linux-64::cudnn-8.4.1.50-hed8a83a_0
#   frozenlist         conda-forge/linux-64::frozenlist-1.3.1-py39hb9d737c_0
#   gast               conda-forge/noarch::gast-0.5.3-pyhd8ed1ab_0
#   giflib             conda-forge/linux-64::giflib-5.2.1-h36c2ea0_2
#   google-auth        conda-forge/noarch::google-auth-2.10.0-pyh6c4a22f_0
#   google-auth-oauth~ conda-forge/noarch::google-auth-oauthlib-0.4.6-pyhd8ed1ab_0
#   google-pasta       conda-forge/noarch::google-pasta-0.2.0-pyh8c360ce_0
#   grpcio             conda-forge/linux-64::grpcio-1.45.0-py39h0f497a6_0
#   h5py               conda-forge/linux-64::h5py-3.7.0-nompi_py39h63b1161_100
#   hdf5               conda-forge/linux-64::hdf5-1.12.1-nompi_h2386368_104
#   icu                conda-forge/linux-64::icu-70.1-h27087fc_0
#   idna               conda-forge/noarch::idna-3.3-pyhd8ed1ab_0
#   importlib-metadata conda-forge/linux-64::importlib-metadata-4.11.4-py39hf3d152e_0
#   jpeg               conda-forge/linux-64::jpeg-9e-h166bdaf_2
#   keras              conda-forge/noarch::keras-2.8.0-pyhd8ed1ab_0
#   keras-preprocessi~ conda-forge/noarch::keras-preprocessing-1.1.2-pyhd8ed1ab_0
#   libpng             conda-forge/linux-64::libpng-1.6.37-h753d276_3
#   markdown           conda-forge/noarch::markdown-3.4.1-pyhd8ed1ab_0
#   markupsafe         conda-forge/linux-64::markupsafe-2.1.1-py39hb9d737c_1
#   multidict          conda-forge/linux-64::multidict-6.0.2-py39hb9d737c_1
#   nccl               conda-forge/linux-64::nccl-2.13.4.1-h0800d71_0
#   oauthlib           conda-forge/noarch::oauthlib-3.2.0-pyhd8ed1ab_0
#   opt_einsum         conda-forge/noarch::opt_einsum-3.3.0-pyhd8ed1ab_1
#   pyasn1             conda-forge/noarch::pyasn1-0.4.8-py_0
#   pyasn1-modules     conda-forge/noarch::pyasn1-modules-0.2.7-py_0
#   pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
#   pyjwt              conda-forge/noarch::pyjwt-2.4.0-pyhd8ed1ab_0
#   pyopenssl          conda-forge/noarch::pyopenssl-22.0.0-pyhd8ed1ab_0
#   pysocks            conda-forge/linux-64::pysocks-1.7.1-py39hf3d152e_5
#   python-flatbuffers conda-forge/noarch::python-flatbuffers-2.0-pyhd8ed1ab_0
#   pyu2f              conda-forge/noarch::pyu2f-0.1.5-pyhd8ed1ab_0
#   requests           conda-forge/noarch::requests-2.28.1-pyhd8ed1ab_0
#   requests-oauthlib  conda-forge/noarch::requests-oauthlib-1.3.1-pyhd8ed1ab_0
#   rsa                conda-forge/noarch::rsa-4.9-pyhd8ed1ab_0
#   scipy              conda-forge/linux-64::scipy-1.9.0-py39h8ba3f38_0
#   tensorboard        conda-forge/noarch::tensorboard-2.8.0-pyhd8ed1ab_1
#   tensorboard-data-~ conda-forge/linux-64::tensorboard-data-server-0.6.0-py39hd97740a_2
#   tensorboard-plugi~ conda-forge/noarch::tensorboard-plugin-wit-1.8.1-pyhd8ed1ab_0
#   tensorflow         conda-forge/linux-64::tensorflow-2.8.1-cuda112py39h01bd6f0_0
#   tensorflow-base    conda-forge/linux-64::tensorflow-base-2.8.1-cuda112py39he716a45_0
#   tensorflow-estima~ conda-forge/linux-64::tensorflow-estimator-2.8.1-cuda112py39hd320b7a_0
#   tensorflow-gpu     conda-forge/linux-64::tensorflow-gpu-2.8.1-cuda112py39h0bbbad9_0
#   termcolor          conda-forge/noarch::termcolor-1.1.0-pyhd8ed1ab_3
#   typing-extensions  conda-forge/noarch::typing-extensions-4.3.0-hd8ed1ab_0
#   urllib3            conda-forge/noarch::urllib3-1.26.11-pyhd8ed1ab_0
#   werkzeug           conda-forge/noarch::werkzeug-2.2.1-pyhd8ed1ab_0
#   wrapt              conda-forge/linux-64::wrapt-1.14.1-py39hb9d737c_0
#   yarl               conda-forge/linux-64::yarl-1.7.2-py39hb9d737c_2
#   zipp               conda-forge/noarch::zipp-3.8.1-pyhd8ed1ab_0

# The following packages will be DOWNGRADED:

#   abseil-cpp                          20211102.0-h27087fc_1 --> 20210324.2-h9c3ff4c_0
#   arrow-cpp                       7.0.0-py39h0f417f0_8_cuda --> 7.0.0-py39he577829_7_cuda
#   grpc-cpp                                1.46.3-hc275302_1 --> 1.45.2-hd8f4eba_3
#   libgoogle-cloud                         1.40.2-hefc27d0_0 --> 1.40.2-habd0e3a_0
#   orc                                      1.7.5-h6c59b99_0 --> 1.7.3-h6c59b99_1
#   pyarrow                         7.0.0-py39h1ed2e5d_8_cuda --> 7.0.0-py39h1ed2e5d_7_cuda
# RUN conda install -n venv -c conda-forge \
#     pyarrow=7.0.0 \
#     arrow-cpp=7.0.0 \
#     grpc-cpp=1.45.2 \
#     scipy=1.9.0

# -------------------------------------------------
# name: venv
# dependencies:
#  - tensorflow=2.8.1-cuda112py39h01bd6f0_0
#  - tensorflow-gpu=2.8.1-cuda112py39h0bbbad9_0
# abseil-cpp=20210324.2 \
# arrow-cpp=7.0.0 \
# grpc-cpp=1.45.2 \
# libgoogle-cloud=1.40.2 \
# orc=1.7.3-h6c59b99_1 \
# pyarrow=7.0.0
# -------------------------------------------------

# Proceed ([y]/n)? y


# Downloading and Extracting Packages
# keras-2.8.0          | 879 KB    | ############################################################################################### | 100% 
# tensorboard-data-ser | 3.1 MB    | ############################################################################################### | 100% 
# brotlipy-0.7.0       | 342 KB    | ############################################################################################### | 100% 
# urllib3-1.26.11      | 102 KB    | ############################################################################################### | 100% 
# cached_property-1.5. | 11 KB     | ############################################################################################### | 100% 
# pysocks-1.7.1        | 28 KB     | ############################################################################################### | 100% 
# tensorflow-estimator | 653 KB    | ############################################################################################### | 100% 
# oauthlib-3.2.0       | 90 KB     | ############################################################################################### | 100% 
# libgoogle-cloud-1.40 | 9.2 MB    | ############################################################################################### | 100% 
# libpng-1.6.37        | 331 KB    | ############################################################################################### | 100% 
# pycparser-2.21       | 100 KB    | ############################################################################################### | 100% 
# grpcio-1.45.0        | 2.5 MB    | ############################################################################################### | 100% 
# tensorflow-gpu-2.8.1 | 26 KB     | ############################################################################################### | 100% 
# frozenlist-1.3.1     | 44 KB     | ############################################################################################### | 100% 
# tensorboard-2.8.0    | 5.2 MB    | ############################################################################################### | 100% 
# cached-property-1.5. | 4 KB      | ############################################################################################### | 100% 
# markupsafe-2.1.1     | 22 KB     | ############################################################################################### | 100% 
# idna-3.3             | 55 KB     | ############################################################################################### | 100% 
# pyu2f-0.1.5          | 31 KB     | ############################################################################################### | 100% 
# google-auth-oauthlib | 19 KB     | ############################################################################################### | 100% 
# werkzeug-2.2.1       | 238 KB    | ############################################################################################### | 100% 
# orc-1.7.3            | 1.1 MB    | ############################################################################################### | 100% 
# pyopenssl-22.0.0     | 49 KB     | ############################################################################################### | 100% 
# charset-normalizer-2 | 35 KB     | ############################################################################################### | 100% 
# rsa-4.9              | 29 KB     | ############################################################################################### | 100% 
# arrow-cpp-7.0.0      | 24.3 MB   | ############################################################################################### | 100% 
# wrapt-1.14.1         | 50 KB     | ############################################################################################### | 100% 
# hdf5-1.12.1          | 3.5 MB    | ############################################################################################### | 100% 
# pyjwt-2.4.0          | 19 KB     | ############################################################################################### | 100% 
# pyasn1-modules-0.2.7 | 60 KB     | ############################################################################################### | 100% 
# cryptography-37.0.4  | 1.5 MB    | ############################################################################################### | 100% 
# pyarrow-7.0.0        | 3.0 MB    | ############################################################################################### | 100% 
# typing-extensions-4. | 8 KB      | ############################################################################################### | 100% 
# abseil-cpp-20210324. | 1010 KB   | ############################################################################################### | 100% 
# termcolor-1.1.0      | 8 KB      | ############################################################################################### | 100% 
# multidict-6.0.2      | 51 KB     | ############################################################################################### | 100% 
# zipp-3.8.1           | 13 KB     | ############################################################################################### | 100% 
# cffi-1.15.1          | 229 KB    | ############################################################################################### | 100% 
# click-8.1.3          | 146 KB    | ############################################################################################### | 100% 
# google-pasta-0.2.0   | 42 KB     | ############################################################################################### | 100% 
# aiosignal-1.2.0      | 12 KB     | ############################################################################################### | 100% 
# h5py-3.7.0           | 1.3 MB    | ############################################################################################### | 100% 
# grpc-cpp-1.45.2      | 4.7 MB    | ############################################################################################### | 100% 
# blinker-1.4          | 13 KB     | ############################################################################################### | 100% 
# astunparse-1.6.3     | 15 KB     | ############################################################################################### | 100% 
# cudnn-8.4.1.50       | 618.4 MB  | ############################################################################################### | 100% 
# yarl-1.7.2           | 132 KB    | ############################################################################################### | 100% 
# absl-py-1.2.0        | 94 KB     | ############################################################################################### | 100% 
# requests-2.28.1      | 53 KB     | ############################################################################################### | 100% 
# pyasn1-0.4.8         | 53 KB     | ############################################################################################### | 100% 
# google-auth-2.10.0   | 90 KB     | ############################################################################################### | 100% 
# icu-70.1             | 13.5 MB   | ############################################################################################### | 100% 
# tensorflow-base-2.8. | 396.2 MB  | ############################################################################################### | 100% 
# nccl-2.13.4.1        | 133.8 MB  | ############################################################################################### | 100% 
# importlib-metadata-4 | 33 KB     | ############################################################################################### | 100% 
# keras-preprocessing- | 34 KB     | ############################################################################################### | 100% 
# aiohttp-3.8.1        | 565 KB    | ############################################################################################### | 100% 
# async-timeout-4.0.2  | 9 KB      | ############################################################################################### | 100% 
# opt_einsum-3.3.0     | 53 KB     | ############################################################################################### | 100% 
# giflib-5.2.1         | 77 KB     | ############################################################################################### | 100% 
# gast-0.5.3           | 20 KB     | ############################################################################################### | 100% 
# python-flatbuffers-2 | 28 KB     | ############################################################################################### | 100% 
# tensorboard-plugin-w | 668 KB    | ############################################################################################### | 100% 
# requests-oauthlib-1. | 22 KB     | ############################################################################################### | 100% 
# markdown-3.4.1       | 65 KB     | ############################################################################################### | 100% 
# scipy-1.9.0          | 26.2 MB   | ############################################################################################### | 100% 
# attrs-22.1.0         | 48 KB     | ############################################################################################### | 100% 
# tensorflow-2.8.1     | 26 KB     | ############################################################################################### | 100% 
# jpeg-9e              | 269 KB    | ############################################################################################### | 100% 
# certifi-2022.6.15    | 155 KB    | ############################################################################################### | 100% 
# Preparing transaction: done
# Verifying transaction: done
# Executing transaction: / By downloading and using the cuDNN conda packages, you accept the terms and conditions of the NVIDIA cuDNN EULA -
#   https://docs.nvidia.com/deeplearning/cudnn/sla/index.html

# done